######################################################################
# Automatically generated by qmake (3.0) st lis 25 22:02:19 2015
######################################################################

TEMPLATE = app
TARGET = qtFract
QT += core gui
QT += widgets
INCLUDEPATH += .

# Input
HEADERS += fractal.h fractGUI.h jpgd.h jpge.h params.h tga.h
SOURCES += Fract.cc fractal.cc fractGUI.cc jpgd.cpp jpge.cpp params.cc tga.cc
